# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-10-25 01:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='action',
            options={'verbose_name': '处理动作', 'verbose_name_plural': '处理动作'},
        ),
        migrations.AlterModelOptions(
            name='actionoperation',
            options={'verbose_name': '动作升级', 'verbose_name_plural': '动作升级'},
        ),
        migrations.AlterModelOptions(
            name='host',
            options={'verbose_name': '监控的主机', 'verbose_name_plural': '监控的主机'},
        ),
        migrations.AlterModelOptions(
            name='hostgroup',
            options={'verbose_name': '监控的主机组', 'verbose_name_plural': '监控的主机组'},
        ),
        migrations.AlterModelOptions(
            name='maintenance',
            options={'verbose_name': '其他', 'verbose_name_plural': '其他'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name': '监控项目', 'verbose_name_plural': '监控项目'},
        ),
        migrations.AlterModelOptions(
            name='serviceindex',
            options={'verbose_name': '监控指标', 'verbose_name_plural': '监控指标'},
        ),
        migrations.AlterModelOptions(
            name='template',
            options={'verbose_name': '监控模板', 'verbose_name_plural': '监控模板'},
        ),
        migrations.AlterModelOptions(
            name='trigger',
            options={'verbose_name': '触发器', 'verbose_name_plural': '触发器'},
        ),
        migrations.AlterModelOptions(
            name='triggerexpression',
            options={'verbose_name': '触发器表达式', 'verbose_name_plural': '触发器表达式'},
        ),
        migrations.AddField(
            model_name='userprofile',
            name='email',
            field=models.EmailField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='qq',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='weixin',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
